version: '2'
services:
  mosquitto:
    image: eclipse-mosquitto:1.6.8
    hostname: mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes: 
      - ./volume/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./volume/data:/mosquitto/data
      - ./volume/log:/mosquitto/log