apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka-server
  namespace: site
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: registry
          image: alanecust/eureka-server:v1
          ports:
          - name: http
            containerPort: 8761
  serviceName: eureka-server-svc

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server-headless-svc
spec:
  clusterIP: None
  selector:
    app: eureka-server
  ports:
    - name: http
      port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server-nodepoint-svc
  namespace: site
spec:
  type: NodePort
  selector:
    app: eureka-server
  ports:
    - name: http
      nodePort: 30001
      port: 8761
      targetPort: 8761